### ISSUE TITLE
where the file config.json should be located? 

### ISSUE THREAD

**Issue by rgxOS** [al-swaiti/ComfyUI-OllamaGemini#13]
hi i locate config.json in ~/ComfyUI/custom_nodes/ComfyUI-OllamaGemini , but it's not readable. where's the correct location? 

def get_gemini_api_key():
    try:
        config_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'config.json')
        with open(config_path, 'r') as f:  
            config = json.load(f)
        api_key = config["GEMINI_API_KEY"]
    except:
        print("Error: Gemini API key is required")
        return ""
    return api_key

**Comment by skarlekar** [comment]
I found the config.json in the custom nodes directory: ComfyUI\custom_nodes\ComfyUI-OllamaGemini. Hope this helps.

**Comment by rgxOS** [comment]
work perfectly now. thx !
