### ISSUE TITLE
Output from the call to Gemini/Ollama

### ISSUE THREAD

**Issue by skarlekar** [al-swaiti/ComfyUI-OllamaGemini#14]
I am new to ComfyUI. Is there a way to see the actual output from the call to Gemini or Ollama? As the output is directly stringed to the ClipTextEncoder, I am unable to see the outputs from the call to the LLMs.  I would be fine if it is just in the logs. Any pointers will be appreciated.

**Comment by al-swaiti** [comment]
lets try gemini firstly create your api key 

https://aistudio.google.com/app/apikey just login here and click get api key and create any new project for that
[
![2024-12-25_12-08](https://github.com/user-attachments/assets/95c5d004-ad57-49bb-9718-5581fc9048a7)
](url)
then

**Comment by al-swaiti** [comment]
https://github.com/user-attachments/assets/6ea20eb8-2267-4826-bf54-5a602be5bfd2

**Comment by al-swaiti** [comment]
for ollama u must install ollama first and download any ai model , then the ai model will be apear auto at list
