### ISSUE TITLE
api key 

### ISSUE THREAD

**Issue by labesx** [al-swaiti/ComfyUI-OllamaGemini#7]
how to get api key

**Comment by al-swaiti** [comment]
https://aistudio.google.com/app/apikey just login here and click get api key and create any new project for that

**Comment by rgxOS** [comment]
hi i copy api key in config.json but comfyui still give me an error "Gemini API key is required". how to solve it?

File "/home/software/ComfyUI/custom_nodes/ComfyUI-OllamaGemini/GeminiOllamaNode.py", line 73, in generate_content
    raise ValueError("Gemini API key is required")
ValueError: Gemini API key is required

**Comment by al-swaiti** [comment]
![2024-12-25_12-07](https://github.com/user-attachments/assets/96183c4d-30eb-43eb-9df2-03c8f43dfe4c)
![2024-12-25_12-08](https://github.com/user-attachments/assets/53050413-ba69-4565-8ff7-5a7860ccfa8a)
